{
 "title": "ProcessingUnit-faresandrules",
 "time": { "from": "2018-11-20T21:25:36.606Z", "to": "2018-11-20T21:27:11.790Z" },
 "panels": [
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Used Memory (bytes)" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT sum(value) FROM \"jvm_memory_heap_used-bytes\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Used CPU (%)" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "process_cpu_used-percent",
     "query": "SELECT sum(value) FROM \"process_cpu_used-percent\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_count",
     "query": "SELECT sum(value) FROM \"jvm_threads_count\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "Off Heap Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Off Heap Used" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_off-heap_used-bytes_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "space_blobstore_get-tp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "space_blobstore_get-tp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_get-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "space_blobstore_cache-size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_cache-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "Off Heap for Products",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_off-heap_used-bytes_org.insightedge.examples.basic.Product",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "hit/miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "space_blobstore_cache-hit/miss" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_cache-hit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_blobstore_cache-miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  { "title": "LRMI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "LRMI Default Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "lrmi_connection-pool_active-threads",
     "query": "SELECT sum(value) FROM \"lrmi_connection-pool_active-threads\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "LRMI Liveness Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "lrmi_liveness-pool_active-threads",
     "query": "SELECT sum(value) FROM \"lrmi_liveness-pool_active-threads\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "LRMI Monitoring Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "lrmi_monitoring-pool_active-threads",
     "query": "SELECT sum(value) FROM \"lrmi_monitoring-pool_active-threads\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  },
  {
   "title": "LRMI Custom Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "sum", "name": "value" }
     ],
     "measurement": "lrmi_custom-pool_active-threads",
     "query": "SELECT sum(value) FROM \"lrmi_custom-pool_active-threads\" WHERE pu_name='faresandrules' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=", "value": "faresandrules" }
     ]
    }
   ]
  }
 ]
}